spring:
  profiles:
    #运行的环境
    active: test
  application:
    name: calyeechat
  datasource:
    url: jdbc:mysql://${calyeechat.mysql.ip}:${calyeechat.mysql.port}/${calyeechat.mysql.db}?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: ${calyeechat.mysql.username}
    password: ${calyeechat.mysql.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    # Redis服务器地址
    host: ${calyeechat.redis.host}
    # Redis服务器端口号
    port: ${calyeechat.redis.port}
    # 使用的数据库索引，默认是0
    database: 0
    # 连接超时时间
    timeout: 1800000
    # 设置密码
    password: ${calyeechat.redis.password}
  jackson:
    serialization:
      write-dates-as-timestamps: true